/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as MarketingLayoutRouteRouteImport } from './routes/_marketing-layout/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MarketingLayoutIndexRouteImport } from './routes/_marketing-layout/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as MarketingLayoutAboutRouteImport } from './routes/_marketing-layout/about'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingLayoutRouteRoute = MarketingLayoutRouteRouteImport.update({
  id: '/_marketing-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const MarketingLayoutIndexRoute = MarketingLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingLayoutRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const MarketingLayoutAboutRoute = MarketingLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingLayoutIndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof MarketingLayoutAboutRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof MarketingLayoutAboutRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/': typeof MarketingLayoutIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing-layout': typeof MarketingLayoutRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_marketing-layout/about': typeof MarketingLayoutAboutRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/_marketing-layout/': typeof MarketingLayoutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/dashboard' | '/about' | '/dashboard/settings' | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/dashboard/settings' | '/' | '/dashboard'
  id:
    | '__root__'
    | '/_marketing-layout'
    | '/dashboard'
    | '/_marketing-layout/about'
    | '/dashboard/settings'
    | '/_marketing-layout/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingLayoutRouteRoute: typeof MarketingLayoutRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing-layout': {
      id: '/_marketing-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_marketing-layout/': {
      id: '/_marketing-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingLayoutIndexRouteImport
      parentRoute: typeof MarketingLayoutRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_marketing-layout/about': {
      id: '/_marketing-layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingLayoutAboutRouteImport
      parentRoute: typeof MarketingLayoutRouteRoute
    }
  }
}

interface MarketingLayoutRouteRouteChildren {
  MarketingLayoutAboutRoute: typeof MarketingLayoutAboutRoute
  MarketingLayoutIndexRoute: typeof MarketingLayoutIndexRoute
}

const MarketingLayoutRouteRouteChildren: MarketingLayoutRouteRouteChildren = {
  MarketingLayoutAboutRoute: MarketingLayoutAboutRoute,
  MarketingLayoutIndexRoute: MarketingLayoutIndexRoute,
}

const MarketingLayoutRouteRouteWithChildren =
  MarketingLayoutRouteRoute._addFileChildren(MarketingLayoutRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingLayoutRouteRoute: MarketingLayoutRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
