/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MarketingRouteRouteImport } from './routes/_marketing/route'
import { Route as ExamplesRouteRouteImport } from './routes/examples/route'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as ExamplesIndexRouteImport } from './routes/examples/index'
import { Route as ExamplesSettingsRouteImport } from './routes/examples/settings'
import { Route as ExamplesUsersRouteRouteImport } from './routes/examples/users/route'
import { Route as ExamplesUsersIndexRouteImport } from './routes/examples/users/index'
import { Route as ExamplesUsersUserIdRouteImport } from './routes/examples/users/$userId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRouteRoute = MarketingRouteRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRouteRoute = ExamplesRouteRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const ExamplesIndexRoute = ExamplesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamplesRouteRoute,
} as any)
const ExamplesSettingsRoute = ExamplesSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ExamplesRouteRoute,
} as any)
const ExamplesUsersRouteRoute = ExamplesUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ExamplesRouteRoute,
} as any)
const ExamplesUsersIndexRoute = ExamplesUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamplesUsersRouteRoute,
} as any)
const ExamplesUsersUserIdRoute = ExamplesUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ExamplesUsersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/examples': typeof ExamplesRouteRouteWithChildren
  '/examples/users': typeof ExamplesUsersRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/about': typeof MarketingAboutRoute
  '/examples/settings': typeof ExamplesSettingsRoute
  '/examples/': typeof ExamplesIndexRoute
  '/examples/users/$userId': typeof ExamplesUsersUserIdRoute
  '/examples/users/': typeof ExamplesUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/about': typeof MarketingAboutRoute
  '/examples/settings': typeof ExamplesSettingsRoute
  '/examples': typeof ExamplesIndexRoute
  '/examples/users/$userId': typeof ExamplesUsersUserIdRoute
  '/examples/users': typeof ExamplesUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_marketing': typeof MarketingRouteRouteWithChildren
  '/examples': typeof ExamplesRouteRouteWithChildren
  '/examples/users': typeof ExamplesUsersRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/examples/settings': typeof ExamplesSettingsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/examples/': typeof ExamplesIndexRoute
  '/examples/users/$userId': typeof ExamplesUsersUserIdRoute
  '/examples/users/': typeof ExamplesUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/examples'
    | '/examples/users'
    | '/login'
    | '/register'
    | '/about'
    | '/examples/settings'
    | '/examples/'
    | '/examples/users/$userId'
    | '/examples/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/about'
    | '/examples/settings'
    | '/examples'
    | '/examples/users/$userId'
    | '/examples/users'
  id:
    | '__root__'
    | '/_auth'
    | '/_marketing'
    | '/examples'
    | '/examples/users'
    | '/_auth/login'
    | '/_auth/register'
    | '/_marketing/about'
    | '/examples/settings'
    | '/_marketing/'
    | '/examples/'
    | '/examples/users/$userId'
    | '/examples/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MarketingRouteRoute: typeof MarketingRouteRouteWithChildren
  ExamplesRouteRoute: typeof ExamplesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/examples/': {
      id: '/examples/'
      path: '/'
      fullPath: '/examples/'
      preLoaderRoute: typeof ExamplesIndexRouteImport
      parentRoute: typeof ExamplesRouteRoute
    }
    '/examples/settings': {
      id: '/examples/settings'
      path: '/settings'
      fullPath: '/examples/settings'
      preLoaderRoute: typeof ExamplesSettingsRouteImport
      parentRoute: typeof ExamplesRouteRoute
    }
    '/examples/users': {
      id: '/examples/users'
      path: '/users'
      fullPath: '/examples/users'
      preLoaderRoute: typeof ExamplesUsersRouteRouteImport
      parentRoute: typeof ExamplesRouteRoute
    }
    '/examples/users/': {
      id: '/examples/users/'
      path: '/'
      fullPath: '/examples/users/'
      preLoaderRoute: typeof ExamplesUsersIndexRouteImport
      parentRoute: typeof ExamplesUsersRouteRoute
    }
    '/examples/users/$userId': {
      id: '/examples/users/$userId'
      path: '/$userId'
      fullPath: '/examples/users/$userId'
      preLoaderRoute: typeof ExamplesUsersUserIdRouteImport
      parentRoute: typeof ExamplesUsersRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(AuthRouteRouteChildren)

interface MarketingRouteRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteRouteChildren: MarketingRouteRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteRouteWithChildren = MarketingRouteRoute._addFileChildren(
  MarketingRouteRouteChildren,
)

interface ExamplesUsersRouteRouteChildren {
  ExamplesUsersUserIdRoute: typeof ExamplesUsersUserIdRoute
  ExamplesUsersIndexRoute: typeof ExamplesUsersIndexRoute
}

const ExamplesUsersRouteRouteChildren: ExamplesUsersRouteRouteChildren = {
  ExamplesUsersUserIdRoute: ExamplesUsersUserIdRoute,
  ExamplesUsersIndexRoute: ExamplesUsersIndexRoute,
}

const ExamplesUsersRouteRouteWithChildren = ExamplesUsersRouteRoute._addFileChildren(
  ExamplesUsersRouteRouteChildren,
)

interface ExamplesRouteRouteChildren {
  ExamplesUsersRouteRoute: typeof ExamplesUsersRouteRouteWithChildren
  ExamplesSettingsRoute: typeof ExamplesSettingsRoute
  ExamplesIndexRoute: typeof ExamplesIndexRoute
}

const ExamplesRouteRouteChildren: ExamplesRouteRouteChildren = {
  ExamplesUsersRouteRoute: ExamplesUsersRouteRouteWithChildren,
  ExamplesSettingsRoute: ExamplesSettingsRoute,
  ExamplesIndexRoute: ExamplesIndexRoute,
}

const ExamplesRouteRouteWithChildren = ExamplesRouteRoute._addFileChildren(
  ExamplesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MarketingRouteRoute: MarketingRouteRouteWithChildren,
  ExamplesRouteRoute: ExamplesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
