import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { RscBoundaryProvider } from 'rsc-boundary'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Next.js App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const isDev = process.env.NODE_ENV === 'development'

  if (!isDev) {
    return (
      <html lang="en" className={cn('h-full', 'antialiased', 'font-sans', roboto.variable)}>
        <body className="min-h-full flex flex-col">{children}</body>
      </html>
    )
  }
  return (
    <html lang="en" className={cn('h-full', 'antialiased', 'font-sans', roboto.variable)}>
      <body className="min-h-full flex flex-col">
        <RscBoundaryProvider>{children}</RscBoundaryProvider>
      </body>
    </html>
  )
}
